# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ffacefe4447fd2251711b492d822502d"
name = "hiive-test"
handle = "hiive-test"
application_url = "https://never-copper-long-forge.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-taras-sad.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://never-copper-long-forge.trycloudflare.com/auth/callback",
  "https://never-copper-long-forge.trycloudflare.com/auth/shopify/callback",
  "https://never-copper-long-forge.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
