# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b603b93502c1a54bb020756c36ea9cd"
name = "Hiive"
handle = "hiive"
application_url = "https://sh-brand-admin.joinhiive.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,write_product_listings,write_products,write_publications"

[auth]
redirect_urls = [
  "https://sh-brand-admin.joinhiive.com/auth/callback",
  "https://sh-brand-admin.joinhiive.com/auth/shopify/callback",
  "https://sh-brand-admin.joinhiive.com/api/auth/callback"
]
[webhooks]
api_version = "2024-07"

[pos]
embedded = false
