# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b603b93502c1a54bb020756c36ea9cd"
name = "Hiive"
handle = "Hiive"
application_url = "https://shopify-brand-admin.joinhiive.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shopify-brand-admin.joinhiive.com/auth/callback",
  "https://shopify-brand-admin.joinhiive.com/auth/shopify/callback",
  "https://shopify-brand-admin.joinhiive.com/api/auth/callback"
]
[webhooks]
api_version = "2024-07"

[pos]
embedded = false
